export const regions = [
  { title: "АР Крым", value: "55" },
  { title: "Винницкая", value: "59" },
  { title: "Волынская", value: "66" },
  { title: "Днепропетровская", value: "75" },
  { title: "Донецкая", value: "76" },
  { title: "Житомирская", value: "60" },
  { title: "Закарпатская", value: "63" },
  { title: "Запорожская", value: "69" },
  { title: "Ивано-Франковская", value: "71" },
  { title: "Киевская", value: "56" },
  { title: "Кировоградская", value: "70" },
  { title: "Луганская", value: "72" },
  { title: "Львовская", value: "79" },
  { title: "Николаевская", value: "62" },
  { title: "Одесская", value: "58" },
  { title: "Полтавская", value: "78" },
  { title: "Ровенская", value: "65" },
  { title: "Сумская", value: "68" },
  { title: "Тернопольская", value: "64" },
  { title: "Харьковская", value: "57" },
  { title: "Херсонская", value: "67" },
  { title: "Хмельницкая", value: "77" },
  { title: "Черкасская", value: "74" },
  { title: "Черниговская", value: "61" },
  { title: "Черновицкая", value: "73" },
];
